//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop.FailFastValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StartCropPeriodFailFast {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartCropPeriodFailFast() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.FailFastValidation.StartCropPeriodFailFast", typeof(StartCropPeriodFailFast).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo marca é obrigatório.
        /// </summary>
        public static string CreateBrandCropBrandRequired {
            get {
                return ResourceManager.GetString("CreateBrandCropBrandRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo identificador da safra é obrigatório.
        /// </summary>
        public static string CreateBrandCropCropIdRequired {
            get {
                return ResourceManager.GetString("CreateBrandCropCropIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo id é obrigatório.
        /// </summary>
        public static string CropIdRequired {
            get {
                return ResourceManager.GetString("CropIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de apuração do Early payment fora do período da safra.
        /// </summary>
        public static string EarlyPaymentDateOutsideCropPeriod {
            get {
                return ResourceManager.GetString("EarlyPaymentDateOutsideCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de compra 1 é obrigatório.
        /// </summary>
        public static string EndFirstSellinPeriodRequired {
            get {
                return ResourceManager.GetString("EndFirstSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término da vigência da safra é obrigatório.
        /// </summary>
        public static string EndPeriodRequired {
            get {
                return ResourceManager.GetString("EndPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de planejamento da safra é obrigatório.
        /// </summary>
        public static string EndPlanningPeriodRequired {
            get {
                return ResourceManager.GetString("EndPlanningPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de compra 2 é obrigatório.
        /// </summary>
        public static string EndSecondSellinPeriodRequired {
            get {
                return ResourceManager.GetString("EndSecondSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de escoamento é obrigatório.
        /// </summary>
        public static string EndSelloutPeriodRequired {
            get {
                return ResourceManager.GetString("EndSelloutPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 1º período da safra.
        /// </summary>
        public static string FirstSellinPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("FirstSellinPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do arquivo selecionado não corresponde ao esperado.
        /// </summary>
        public static string ImportExcelBrandCropUnexpectedFormat {
            get {
                return ResourceManager.GetString("ImportExcelBrandCropUnexpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O IntegrationId deve ser diferente de empty.
        /// </summary>
        public static string IntegrationIdMustBeNotEmpty {
            get {
                return ResourceManager.GetString("IntegrationIdMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo plano de metas valorado é obrigatório.
        /// </summary>
        public static string IsGoalPlanningValuedRequired {
            get {
                return ResourceManager.GetString("IsGoalPlanningValuedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome é obrigatório.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de planejamento da safra.
        /// </summary>
        public static string PlanningPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("PlanningPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 2º período da safra..
        /// </summary>
        public static string SecondSellinPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("SecondSellinPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de escoamento da safra.
        /// </summary>
        public static string SelloutPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("SelloutPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 2º período da safra. Este período deve ser posterior ao 1º período de compra da safra..
        /// </summary>
        public static string StartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod {
            get {
                return ResourceManager.GetString("StartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 1º período da safra.
        /// </summary>
        public static string StartFirstSellinPeriodLessThanEndFirstSellinPeriod {
            get {
                return ResourceManager.GetString("StartFirstSellinPeriodLessThanEndFirstSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de compra 1 é obrigatório.
        /// </summary>
        public static string StartFirstSellinPeriodRequired {
            get {
                return ResourceManager.GetString("StartFirstSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de vigência da safra..
        /// </summary>
        public static string StartPeriodLessThanEndPeriod {
            get {
                return ResourceManager.GetString("StartPeriodLessThanEndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início da vigência da safra é obrigatório.
        /// </summary>
        public static string StartPeriodRequired {
            get {
                return ResourceManager.GetString("StartPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de planejamento da safra.
        /// </summary>
        public static string StartPlanningPeriodLessThanEndPlanningPeriod {
            get {
                return ResourceManager.GetString("StartPlanningPeriodLessThanEndPlanningPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de planejamento da safra é obrigatório.
        /// </summary>
        public static string StartPlanningPeriodRequired {
            get {
                return ResourceManager.GetString("StartPlanningPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 2º período da safra.
        /// </summary>
        public static string StartSecondSellinPeriodLessThanEndSecondSellinPeriod {
            get {
                return ResourceManager.GetString("StartSecondSellinPeriodLessThanEndSecondSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de compra 2 é obrigatório.
        /// </summary>
        public static string StartSecondSellinPeriodRequired {
            get {
                return ResourceManager.GetString("StartSecondSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de escoamento da safra.
        /// </summary>
        public static string StartSelloutPeriodLessThanEndSelloutPeriod {
            get {
                return ResourceManager.GetString("StartSelloutPeriodLessThanEndSelloutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de escoamento é obrigatório.
        /// </summary>
        public static string StartSelloutPeriodRequired {
            get {
                return ResourceManager.GetString("StartSelloutPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo identificador da marca é obrigatório.
        /// </summary>
        public static string UpdateBrandCropBrandIntegrationIdRequired {
            get {
                return ResourceManager.GetString("UpdateBrandCropBrandIntegrationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo identificador da safra é obrigatório.
        /// </summary>
        public static string UpdateBrandCropCropIntegrationIdRequired {
            get {
                return ResourceManager.GetString("UpdateBrandCropCropIntegrationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo preço não está no formato esperado, deve conter valor maior que 0.
        /// </summary>
        public static string UpdateBrandCropPriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("UpdateBrandCropPriceMustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
