trigger:
    - develop

stages:
- stage: Build
  displayName: 'Build App'
  jobs:
  - template: azure-pipelines-build-template.yml
    parameters:
      vmImage: 'windows-latest'
      buildConfiguration: 'Release'
      publishProjects: '**/*PX.Approval.API.csproj'