//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop.FailFastValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SaveClassificationCropFailFast {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaveClassificationCropFailFast() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.FailFastValidation.SaveClassificationCropFailFast", typeof(SaveClassificationCropFailFast).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo código da classificação não está no formato esperado.
        /// </summary>
        public static string ClassificationCodeInvalid {
            get {
                return ResourceManager.GetString("ClassificationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo código da classificação é obrigatório.
        /// </summary>
        public static string ClassificationCodeRequired {
            get {
                return ResourceManager.GetString("ClassificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem registros com o campo &apos;código de classificação&apos; preenchidos com o mesmo valor.
        /// </summary>
        public static string ClassificationsMustHaveNoDiplicateClassificationCode {
            get {
                return ResourceManager.GetString("ClassificationsMustHaveNoDiplicateClassificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Não é permitido cadastrar tipo Seeds para Cooperativa.
        /// </summary>
        public static string ClassificationTypeForCoperativeInvalid {
            get {
                return ResourceManager.GetString("ClassificationTypeForCoperativeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Não é permitido colocar valor de margem de planejamento para tipo Seeds.
        /// </summary>
        public static string ClassificationTypeForPlanningMarginInvalid {
            get {
                return ResourceManager.GetString("ClassificationTypeForPlanningMarginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Não é permitido informar 1º período de compras para tipo Seeds.
        /// </summary>
        public static string ClassificationTypeForRequiredFirstPeriodSellIn {
            get {
                return ResourceManager.GetString("ClassificationTypeForRequiredFirstPeriodSellIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo tipo não está no formato esperado.
        /// </summary>
        public static string ClassificationTypeInvalid {
            get {
                return ResourceManager.GetString("ClassificationTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo tipo é obrigatório.
        /// </summary>
        public static string ClassificationTypeRequired {
            get {
                return ResourceManager.GetString("ClassificationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O integration Id da Safra deve ser diferente de empty.
        /// </summary>
        public static string CropIntegrationIdMustBeNotEmpty {
            get {
                return ResourceManager.GetString("CropIntegrationIdMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo % EarlyPayment deve ser entre 0,00 e 100,00.
        /// </summary>
        public static string EarlyPaymentInvalidRange {
            get {
                return ResourceManager.GetString("EarlyPaymentInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo KPIWeight deve ser entre 1 e 9999.
        /// </summary>
        public static string KPIWeightInvalidRange {
            get {
                return ResourceManager.GetString("KPIWeightInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo tipo do parceiro não está no formato esperado.
        /// </summary>
        public static string PartnerTypeInvalid {
            get {
                return ResourceManager.GetString("PartnerTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo tipo parceiro é obrigatório.
        /// </summary>
        public static string PartnerTypeRequired {
            get {
                return ResourceManager.GetString("PartnerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro {CollectionIndex} : Campo margem de planejamento não está no formato esperado.
        /// </summary>
        public static string PlanningMarginInvalid {
            get {
                return ResourceManager.GetString("PlanningMarginInvalid", resourceCulture);
            }
        }
    }
}
