//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop.FailFastValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpdateCropPeriodFailFast {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateCropPeriodFailFast() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.FailFastValidation.UpdateCropPeriodFailFast", typeof(UpdateCropPeriodFailFast).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo id é obrigatório.
        /// </summary>
        public static string UpdateCropCropIdRequired {
            get {
                return ResourceManager.GetString("UpdateCropCropIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de compra 1 é obrigatório.
        /// </summary>
        public static string UpdateCropEndFirstSellinPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropEndFirstSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término da vigência da safra é obrigatório.
        /// </summary>
        public static string UpdateCropEndPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropEndPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de planejamento da safra é obrigatório.
        /// </summary>
        public static string UpdateCropEndPlanningPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropEndPlanningPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de compra 2 é obrigatório.
        /// </summary>
        public static string UpdateCropEndSecondSellinPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropEndSecondSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data de término do período de escoamento é obrigatório.
        /// </summary>
        public static string UpdateCropEndSelloutPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropEndSelloutPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 1º período da safra.
        /// </summary>
        public static string UpdateCropFirstSellinPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("UpdateCropFirstSellinPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo plano de metas valorado é obrigatório.
        /// </summary>
        public static string UpdateCropIsGoalPlanningValuedRequired {
            get {
                return ResourceManager.GetString("UpdateCropIsGoalPlanningValuedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        public static string UpdateCropNameRequired {
            get {
                return ResourceManager.GetString("UpdateCropNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de planejamento da safra.
        /// </summary>
        public static string UpdateCropPlanningPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("UpdateCropPlanningPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 2º período da safra..
        /// </summary>
        public static string UpdateCropSecondSellinPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("UpdateCropSecondSellinPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de escoamento da safra.
        /// </summary>
        public static string UpdateCropSelloutPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("UpdateCropSelloutPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 2º período da safra. Este período deve ser posterior ao 1º período de compra da safra..
        /// </summary>
        public static string UpdateCropStartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod {
            get {
                return ResourceManager.GetString("UpdateCropStartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 1º período da safra.
        /// </summary>
        public static string UpdateCropStartFirstSellinPeriodLessThanEndFirstSellinPeriod {
            get {
                return ResourceManager.GetString("UpdateCropStartFirstSellinPeriodLessThanEndFirstSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de compra 1 é obrigatório.
        /// </summary>
        public static string UpdateCropStartFirstSellinPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropStartFirstSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de vigência da safra..
        /// </summary>
        public static string UpdateCropStartPeriodLessThanEndPeriod {
            get {
                return ResourceManager.GetString("UpdateCropStartPeriodLessThanEndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início da vigência da safra é obrigatório.
        /// </summary>
        public static string UpdateCropStartPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropStartPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de planejamento da safra.
        /// </summary>
        public static string UpdateCropStartPlanningPeriodLessThanEndPlanningPeriod {
            get {
                return ResourceManager.GetString("UpdateCropStartPlanningPeriodLessThanEndPlanningPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de planejamento da safra é obrigatório.
        /// </summary>
        public static string UpdateCropStartPlanningPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropStartPlanningPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de compra do 2º período da safra.
        /// </summary>
        public static string UpdateCropStartSecondSellinPeriodLessThanEndSecondSellinPeriod {
            get {
                return ResourceManager.GetString("UpdateCropStartSecondSellinPeriodLessThanEndSecondSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de compra 2 é obrigatório.
        /// </summary>
        public static string UpdateCropStartSecondSellinPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropStartSecondSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro identificado no período de escoamento da safra.
        /// </summary>
        public static string UpdateCropStartSelloutPeriodLessThanEndSelloutPeriod {
            get {
                return ResourceManager.GetString("UpdateCropStartSelloutPeriodLessThanEndSelloutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo data início do período de escoamento é obrigatório.
        /// </summary>
        public static string UpdateCropStartSelloutPeriodRequired {
            get {
                return ResourceManager.GetString("UpdateCropStartSelloutPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo status é obrigatório.
        /// </summary>
        public static string UpdateCropStatusRequired {
            get {
                return ResourceManager.GetString("UpdateCropStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo descrição não está no formato esperado.
        /// </summary>
        public static string UpdateCropUnexpectedDescriptonFormat {
            get {
                return ResourceManager.GetString("UpdateCropUnexpectedDescriptonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome não está no formato esperado.
        /// </summary>
        public static string UpdateCropUnexpectedNameFormat {
            get {
                return ResourceManager.GetString("UpdateCropUnexpectedNameFormat", resourceCulture);
            }
        }
    }
}
