//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CropMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CropMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.CropMessages", typeof(CropMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao converter o arquivo de relatório de erro.
        /// </summary>
        public static string BrandCropDownloadExcelPurgesErrorToConvertExcel {
            get {
                return ResourceManager.GetString("BrandCropDownloadExcelPurgesErrorToConvertExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum relatório de erro foi encontrado. Por gentileza tente novamente importar as marcas ou entrar em contato com TI..
        /// </summary>
        public static string BrandCropDownloadExcelPurgesFileNoLoaded {
            get {
                return ResourceManager.GetString("BrandCropDownloadExcelPurgesFileNoLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca criada com sucesso.
        /// </summary>
        public static string CreateBrandCropSuccess {
            get {
                return ResourceManager.GetString("CreateBrandCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra criada com sucesso.
        /// </summary>
        public static string CreateCropSuccess {
            get {
                return ResourceManager.GetString("CreateCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento criado com sucesso.
        /// </summary>
        public static string CreateDocumentCropSuccess {
            get {
                return ResourceManager.GetString("CreateDocumentCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao converter o arquivo modelo.
        /// </summary>
        public static string CropPartnersDownloadExcelModelErrorToConvertExcelModel {
            get {
                return ResourceManager.GetString("CropPartnersDownloadExcelModelErrorToConvertExcelModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum parceiro foi cadastrado no cadastro de parceiro. Por gentileza executar a carga prévia de parceiros ou entrar em contato com TI..
        /// </summary>
        public static string CropPartnersDownloadExcelModelFileNoPartnersLoaded {
            get {
                return ResourceManager.GetString("CropPartnersDownloadExcelModelFileNoPartnersLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status da safra não permite a inativação desse documento..
        /// </summary>
        public static string CropStatusNotAllowDocumentInactivation {
            get {
                return ResourceManager.GetString("CropStatusNotAllowDocumentInactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao remover a marca.
        /// </summary>
        public static string DeleteBrandCropError {
            get {
                return ResourceManager.GetString("DeleteBrandCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca removida com sucesso.
        /// </summary>
        public static string DeleteBrandCropSuccess {
            get {
                return ResourceManager.GetString("DeleteBrandCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao remover a classificação.
        /// </summary>
        public static string DeleteClassificationCropError {
            get {
                return ResourceManager.GetString("DeleteClassificationCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação removida com sucesso.
        /// </summary>
        public static string DeleteClassificationSuccess {
            get {
                return ResourceManager.GetString("DeleteClassificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao remover a safra.
        /// </summary>
        public static string DeleteCropError {
            get {
                return ResourceManager.GetString("DeleteCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra removida com sucesso.
        /// </summary>
        public static string DeleteCropSuccess {
            get {
                return ResourceManager.GetString("DeleteCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento removido com sucesso.
        /// </summary>
        public static string DeleteDocumentCropSuccess {
            get {
                return ResourceManager.GetString("DeleteDocumentCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao remover parceiro.
        /// </summary>
        public static string DeletePartnerCropError {
            get {
                return ResourceManager.GetString("DeletePartnerCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parceiro removido com sucesso.
        /// </summary>
        public static string DeletePartnerCropSuccess {
            get {
                return ResourceManager.GetString("DeletePartnerCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status da Safra não permite a inclusão de parceiros na safra..
        /// </summary>
        public static string DonwloadPartnersExcelModelInvalidCropStatus {
            get {
                return ResourceManager.GetString("DonwloadPartnersExcelModelInvalidCropStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O processo de early payment foi iniciado para a safra {0} - {1}.
        /// </summary>
        public static string EarlyPaymentStartProcess {
            get {
                return ResourceManager.GetString("EarlyPaymentStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao iniciar o processo de early payment. Crop:  {0} - {1}.
        /// </summary>
        public static string EarlyPaymentStartProcessErrorWhileStartingProcess {
            get {
                return ResourceManager.GetString("EarlyPaymentStartProcessErrorWhileStartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo sem nenhum parceiro do tipo CP. Crop:  {0} - {1}.
        /// </summary>
        public static string EarlyPaymentStartProcessHasNoChemicalPartners {
            get {
                return ResourceManager.GetString("EarlyPaymentStartProcessHasNoChemicalPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo sem nenhum parceiro do tipo seeds. Crop:  {0} - {1}.
        /// </summary>
        public static string EarlyPaymentStartProcessHasNoSeedsPartners {
            get {
                return ResourceManager.GetString("EarlyPaymentStartProcessHasNoSeedsPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há parceiros elegíveis a early payment nessa safra.
        /// </summary>
        public static string EarlyPaymentStartProcessNoPartnersAvaliable {
            get {
                return ResourceManager.GetString("EarlyPaymentStartProcessNoPartnersAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A safra informada não foi encontrada.
        /// </summary>
        public static string GetAllBrandsCropCropNotExist {
            get {
                return ResourceManager.GetString("GetAllBrandsCropCropNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma safra foi localizada para o parceiro..
        /// </summary>
        public static string GetAllCropsByPartnerNotFound {
            get {
                return ResourceManager.GetString("GetAllCropsByPartnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma safra foi localizada em que há parceiro em Exceção para este Representante..
        /// </summary>
        public static string GetAllCropsByRTVPartnersInExceptionNotFound {
            get {
                return ResourceManager.GetString("GetAllCropsByRTVPartnersInExceptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API indisponível no momento, por gentileza tentar novamente em alguns minutos.
        /// </summary>
        public static string GetAllSAPBrandsUnavailableApiBrands {
            get {
                return ResourceManager.GetString("GetAllSAPBrandsUnavailableApiBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum parceiro foi cadastrado no cadastro de parceiro. Por gentileza executar a carga prévia de parceiros ou entrar em contato com TI..
        /// </summary>
        public static string GetCropPartnersNoPartnersWasFoundPartnersDatabase {
            get {
                return ResourceManager.GetString("GetCropPartnersNoPartnersWasFoundPartnersDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram selecionados parceiros para a safra..
        /// </summary>
        public static string GetCropPartnersNotAssocietedPartnersWithCrop {
            get {
                return ResourceManager.GetString("GetCropPartnersNotAssocietedPartnersWithCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar o excel para listagem dos erros de importação.
        /// </summary>
        public static string GetPartnerCropPurgeImportationErrorOnGenerateExcelFile {
            get {
                return ResourceManager.GetString("GetPartnerCropPurgeImportationErrorOnGenerateExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum erro de importação foi encontrado para esta safra..
        /// </summary>
        public static string GetPartnerCropPurgeImportationNotFound {
            get {
                return ResourceManager.GetString("GetPartnerCropPurgeImportationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada a matriz para o CRMCode: {0}..
        /// </summary>
        public static string HeadqartersNotFoundForThisCRMCode {
            get {
                return ResourceManager.GetString("HeadqartersNotFoundForThisCRMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram encontradas matrizes para o CWID: {0}.
        /// </summary>
        public static string HeadqartersNotFoundForThisRTVCwid {
            get {
                return ResourceManager.GetString("HeadqartersNotFoundForThisRTVCwid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada matriz para o grupo de parceiros: {0}.
        /// </summary>
        public static string HeadquarterNotFoundForThisPartnerGroup {
            get {
                return ResourceManager.GetString("HeadquarterNotFoundForThisPartnerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação de marcas realizada com sucesso..
        /// </summary>
        public static string ImportBrandCrop {
            get {
                return ResourceManager.GetString("ImportBrandCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontramos erros em {0} marcas importadas..
        /// </summary>
        public static string ImportBrandCropErroImport {
            get {
                return ResourceManager.GetString("ImportBrandCropErroImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importação de parceiros realizada com sucesso..
        /// </summary>
        public static string ImportPartnerCrop {
            get {
                return ResourceManager.GetString("ImportPartnerCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontramos {0} erros na importação de parceiros..
        /// </summary>
        public static string ImportPartnerCropErroImport {
            get {
                return ResourceManager.GetString("ImportPartnerCropErroImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado na importação de parceiros..
        /// </summary>
        public static string ImportPartnerCropUnexpectedErrorImport {
            get {
                return ResourceManager.GetString("ImportPartnerCropUnexpectedErrorImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao abrir a safra.
        /// </summary>
        public static string OpenedCropError {
            get {
                return ResourceManager.GetString("OpenedCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra foi aberta com sucesso.
        /// </summary>
        public static string OpenedCropSuccess {
            get {
                return ResourceManager.GetString("OpenedCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado parceiro nesta safra com esse CRMCode.
        /// </summary>
        public static string PartnerCropNotFoundForThisCRMCode {
            get {
                return ResourceManager.GetString("PartnerCropNotFoundForThisCRMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado parceiro para esta safra.
        /// </summary>
        public static string PartnerCropNotFoundForThisCrop {
            get {
                return ResourceManager.GetString("PartnerCropNotFoundForThisCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao processar a solicitação..
        /// </summary>
        public static string RequestManualPartnersLoadErro {
            get {
                return ResourceManager.GetString("RequestManualPartnersLoadErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação efetuada com sucesso..
        /// </summary>
        public static string RequestManualPartnersLoadSuccess {
            get {
                return ResourceManager.GetString("RequestManualPartnersLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar classificações.
        /// </summary>
        public static string SaveClassficationsCropError {
            get {
                return ResourceManager.GetString("SaveClassficationsCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação(ões) salva(s) com sucesso.
        /// </summary>
        public static string SaveClassficationsCropSuccess {
            get {
                return ResourceManager.GetString("SaveClassficationsCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar a marca.
        /// </summary>
        public static string UpdateBrandCropError {
            get {
                return ResourceManager.GetString("UpdateBrandCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca atualizada com sucesso.
        /// </summary>
        public static string UpdateBrandCropSuccess {
            get {
                return ResourceManager.GetString("UpdateBrandCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualiza safra.
        /// </summary>
        public static string UpdateCropError {
            get {
                return ResourceManager.GetString("UpdateCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra atualizada com sucesso.
        /// </summary>
        public static string UpdateCropSuccess {
            get {
                return ResourceManager.GetString("UpdateCropSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao atualizar parceiro.
        /// </summary>
        public static string UpdatePartnerCropError {
            get {
                return ResourceManager.GetString("UpdatePartnerCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parceiro atualizado com sucesso.
        /// </summary>
        public static string UpdatePartnerCropSuccess {
            get {
                return ResourceManager.GetString("UpdatePartnerCropSuccess", resourceCulture);
            }
        }
    }
}
