//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechada.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperativa.
        /// </summary>
        public static string Cooperative {
            get {
                return ResourceManager.GetString("Cooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Químicos.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atacadista.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluída.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuidor.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rascunho.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Revisão.
        /// </summary>
        public static string In_Review {
            get {
                return ResourceManager.GetString("In-Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa.
        /// </summary>
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orfão.
        /// </summary>
        public static string Orphaned {
            get {
                return ResourceManager.GetString("Orphaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Preços.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente Leitura.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário Aprovação.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sementes.
        /// </summary>
        public static string Seeds {
            get {
                return ResourceManager.GetString("Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atacadista.
        /// </summary>
        public static string Wholesaler {
            get {
                return ResourceManager.GetString("Wholesaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
