//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Approval.Domain.Messages.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Approval.Domain.Messages.Messages.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechada.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperativa.
        /// </summary>
        public static string Cooperative {
            get {
                return ResourceManager.GetString("Cooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Químicos.
        /// </summary>
        public static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atacadista.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Partner Experience.
        /// </summary>
        public static string DefaultSender {
            get {
                return ResourceManager.GetString("DefaultSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluída.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuidor.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rascunho.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body {
        ///                font-family: Arial, Helvetica, sans-serif;
        ///                font-size: 12pt;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        Caro #PARCEIRO#,&lt;br/&gt;
        ///        Seu planejamento de metas foi aprovado.&lt;br/&gt;
        ///        Para ver mais detalhes, acesse o Portal do Parceiro.&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        Este e-mail foi enviado pelo sistema.&lt;br/&gt;
        ///        Crop Science - Portal do Parceiro.
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string EmailApprove {
            get {
                return ResourceManager.GetString("EmailApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body {
        ///                font-family: Arial, Helvetica, sans-serif;
        ///                font-size: 12pt;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        Prezado #PARCEIRO#,&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        Seu planejamento de metas foi cancelado e dever ser reavaliado de acordo com o motivo abaixo informado.&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        #MOTIVO#
        ///        &lt;br/&gt;
        ///        Para ver mais detalhes, acesse o Portal do Parceiro.
        ///       &lt;br/&gt;
        ///       Este  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailCancel {
            get {
                return ResourceManager.GetString("EmailCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body {
        ///                font-family: Arial, Helvetica, sans-serif;
        ///                font-size: 12pt;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        Caro #PARCEIRO#,&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        Seu planejamento de metas foi reprovado e dever ser reavaliado de acordo com o motivo abaixo informado.&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        #MOTIVO#
        ///        &lt;br/&gt;
        ///        Para ver mais detalhes, acesse o Portal do Parceiro.
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string EmailReprove {
            get {
                return ResourceManager.GetString("EmailReprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body {
        ///                font-family: Arial, Helvetica, sans-serif;
        ///                font-size: 12pt;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        Prezado #PARCEIRO#,&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        Seu planejamento de metas teve o status retornado e dever ser reavaliado de acordo com o motivo abaixo informado.&lt;br/&gt;
        ///        &lt;br/&gt;
        ///        #MOTIVO#
        ///        &lt;br/&gt;
        ///        Para ver mais detalhes, acesse o Portal do Parceiro.
        ///       &lt;br/&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailReturn {
            get {
                return ResourceManager.GetString("EmailReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Revisão.
        /// </summary>
        public static string In_Review {
            get {
                return ResourceManager.GetString("In-Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noreplay@bayer.com.
        /// </summary>
        public static string NoReplyEmail {
            get {
                return ResourceManager.GetString("NoReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa.
        /// </summary>
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orfão.
        /// </summary>
        public static string Orphaned {
            get {
                return ResourceManager.GetString("Orphaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Preços.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente Leitura.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário Aprovação.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sementes.
        /// </summary>
        public static string Seeds {
            get {
                return ResourceManager.GetString("Seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Portal Parceiro Bayer] - Planejamento de metas aprovado.
        /// </summary>
        public static string SubjectApprove {
            get {
                return ResourceManager.GetString("SubjectApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Portal Parceiro Bayer] - Planejamento de metas cancelado.
        /// </summary>
        public static string SubjectCancel {
            get {
                return ResourceManager.GetString("SubjectCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Portal Parceiro Bayer] - Planejamento de metas reprovado.
        /// </summary>
        public static string SubjectReprove {
            get {
                return ResourceManager.GetString("SubjectReprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Portal Parceiro Bayer] - Planejamento de metas status retornado.
        /// </summary>
        public static string SubjectReturn {
            get {
                return ResourceManager.GetString("SubjectReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atacadista.
        /// </summary>
        public static string Wholesaler {
            get {
                return ResourceManager.GetString("Wholesaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
