//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop.Logger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CropLoggerMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CropLoggerMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.Logger.CropLoggerMessage", typeof(CropLoggerMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao requisitar a API AuthServices LoginSSO. {0}.
        /// </summary>
        public static string IBayerServiceAuthServicesLoginSSOException {
            get {
                return ResourceManager.GetString("IBayerServiceAuthServicesLoginSSOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao requisitar a API AuthServices User By System. {0}.
        /// </summary>
        public static string IBayerServiceAuthServicesUserBySystemException {
            get {
                return ResourceManager.GetString("IBayerServiceAuthServicesUserBySystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao obter os CWIDs. Detalhe do erro {0}.
        /// </summary>
        public static string IBayerServiceGetAllCWIDException {
            get {
                return ResourceManager.GetString("IBayerServiceGetAllCWIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao obter as marcas do banco de marcas. Detalhe do erro {0}.
        /// </summary>
        public static string IBayerServiceGetBrandsException {
            get {
                return ResourceManager.GetString("IBayerServiceGetBrandsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao solicitar a ultima atualização da base de parceiros. Detalhe do erro {0}.
        /// </summary>
        public static string IBayerServiceGetLastPartnerLoadException {
            get {
                return ResourceManager.GetString("IBayerServiceGetLastPartnerLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao obter os parceiros do banco de partners. Detalhe do erro {0}.
        /// </summary>
        public static string IBayerServiceGetPartnersByFiltersAsyncException {
            get {
                return ResourceManager.GetString("IBayerServiceGetPartnersByFiltersAsyncException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao solicitar a atualização das informações adicionais dos parceiros. Detalhe do erro {0}.
        /// </summary>
        public static string IBayerServicePartnerUpdateAdditionalInformationException {
            get {
                return ResourceManager.GetString("IBayerServicePartnerUpdateAdditionalInformationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao solicitar a atualização manual da base de parceiros. Detalhe do erro {0}.
        /// </summary>
        public static string IBayerServiceRequestManualUpdateException {
            get {
                return ResourceManager.GetString("IBayerServiceRequestManualUpdateException", resourceCulture);
            }
        }
    }
}
