//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop.DomainValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenCropValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenCropValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.DomainValidation.OpenCropValidationMessages", typeof(OpenCropValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra já existente com o mesmo nome e período de vigência.
        /// </summary>
        public static string CropExisting {
            get {
                return ResourceManager.GetString("CropExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndFirstSellinPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationEndFirstSellinPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationEndFirstSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndPlanningPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationEndPlanningPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationEndPlanningPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndSecondSellinPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationEndSecondSellinPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationEndSecondSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndSelloutPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationEndSelloutPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationEndSelloutPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsGoalPlanningValuedRequired.
        /// </summary>
        public static string CropPeriodValidationIsGoalPlanningValuedRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationIsGoalPlanningValuedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartFirstSellinPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationStartFirstSellinPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationStartFirstSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPlanningPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationStartPlanningPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationStartPlanningPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSecondSellinPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationStartSecondSellinPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationStartSecondSellinPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSelloutPeriodRequired.
        /// </summary>
        public static string CropPeriodValidationStartSelloutPeriodRequired {
            get {
                return ResourceManager.GetString("CropPeriodValidationStartSelloutPeriodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstSellinPeriodMustBeBetweenCropPeriod.
        /// </summary>
        public static string FirstSellinPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("FirstSellinPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra valorada, é necessário cadastrar algum valor para as marcas do tipo CP.
        /// </summary>
        public static string InvalidCropCPWithInvalidBrandPrice {
            get {
                return ResourceManager.GetString("InvalidCropCPWithInvalidBrandPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string InvalidRegistrationBrands {
            get {
                return ResourceManager.GetString("InvalidRegistrationBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificações.
        /// </summary>
        public static string InvalidRegistrationClassifications {
            get {
                return ResourceManager.GetString("InvalidRegistrationClassifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Períodos da safra.
        /// </summary>
        public static string InvalidRegistrationCropPeriods {
            get {
                return ResourceManager.GetString("InvalidRegistrationCropPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string InvalidRegistrationDocuments {
            get {
                return ResourceManager.GetString("InvalidRegistrationDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parceiros.
        /// </summary>
        public static string InvalidRegistrationPartners {
            get {
                return ResourceManager.GetString("InvalidRegistrationPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status da safra não permite a ativação da safra..
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A safra não foi encontrada.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validação encontrou 1 ou mais cadastros pendentes: {0}.
        /// </summary>
        public static string OpenCropValidationError {
            get {
                return ResourceManager.GetString("OpenCropValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanningPeriodMustBeBetweenCropPeriod.
        /// </summary>
        public static string PlanningPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("PlanningPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondSellinPeriodMustBeBetweenCropPeriod.
        /// </summary>
        public static string SecondSellinPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("SecondSellinPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelloutPeriodMustBeBetweenCropPeriod.
        /// </summary>
        public static string SelloutPeriodMustBeBetweenCropPeriod {
            get {
                return ResourceManager.GetString("SelloutPeriodMustBeBetweenCropPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod.
        /// </summary>
        public static string StartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod {
            get {
                return ResourceManager.GetString("StartDateSecondSellinPeriodMustBeGreaterThanEndFirstSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartFirstSellinPeriodLessThanEndFirstSellinPeriod.
        /// </summary>
        public static string StartFirstSellinPeriodLessThanEndFirstSellinPeriod {
            get {
                return ResourceManager.GetString("StartFirstSellinPeriodLessThanEndFirstSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPeriodLessThanEndPeriod.
        /// </summary>
        public static string StartPeriodLessThanEndPeriod {
            get {
                return ResourceManager.GetString("StartPeriodLessThanEndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPlanningPeriodLessThanEndPlanningPeriod.
        /// </summary>
        public static string StartPlanningPeriodLessThanEndPlanningPeriod {
            get {
                return ResourceManager.GetString("StartPlanningPeriodLessThanEndPlanningPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSecondSellinPeriodLessThanEndSecondSellinPeriod.
        /// </summary>
        public static string StartSecondSellinPeriodLessThanEndSecondSellinPeriod {
            get {
                return ResourceManager.GetString("StartSecondSellinPeriodLessThanEndSecondSellinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSelloutPeriodLessThanEndSelloutPeriod.
        /// </summary>
        public static string StartSelloutPeriodLessThanEndSelloutPeriod {
            get {
                return ResourceManager.GetString("StartSelloutPeriodLessThanEndSelloutPeriod", resourceCulture);
            }
        }
    }
}
