//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.Crop.Domain.Messages.Crop.DomainValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportPartnerCropDomainValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportPartnerCropDomainValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PX.Crop.Domain.Messages.Crop.DomainValidation.ImportPartnerCropDomainValidationMe" +
                            "ssages", typeof(ImportPartnerCropDomainValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A API [AuthServices - Users By System] está indisponível no momento..
        /// </summary>
        public static string APIAuthServicesUserBySystem {
            get {
                return ResourceManager.GetString("APIAuthServicesUserBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código C360 {0} não localizado. Parceiro não será inserido/atualizado..
        /// </summary>
        public static string C360CodeNotExists {
            get {
                return ResourceManager.GetString("C360CodeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [Código C360] é obrigatório. O Parceiro não será inserido/atualizado..
        /// </summary>
        public static string C360CodeRequired {
            get {
                return ResourceManager.GetString("C360CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ {0} esta duplicado. O Parceiro não será atualizado.
        /// </summary>
        public static string CNPJDuplicated {
            get {
                return ResourceManager.GetString("CNPJDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ {0} não localizado. Parceiro não será atualizado..
        /// </summary>
        public static string CNPJInvalid {
            get {
                return ResourceManager.GetString("CNPJInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [CNPJ] é obrigatório. O Parceiro não será inserido/atualizado..
        /// </summary>
        public static string CNPJRequired {
            get {
                return ResourceManager.GetString("CNPJRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWID {0} não localizado. Parceiro não será atualizado..
        /// </summary>
        public static string CPApproveCWIDInvalid {
            get {
                return ResourceManager.GetString("CPApproveCWIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [ CRMCode ] é obrigatório. O Parceiro não será inserido/atualizado..
        /// </summary>
        public static string CRMCodeRequired {
            get {
                return ResourceManager.GetString("CRMCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} inválido. Parceiro não será atualizado..
        /// </summary>
        public static string EmailCampaignsDocumentsInvalid {
            get {
                return ResourceManager.GetString("EmailCampaignsDocumentsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} inválido. Parceiro não será atualizado..
        /// </summary>
        public static string EmailGoalsPlanningInvalid {
            get {
                return ResourceManager.GetString("EmailGoalsPlanningInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} inválido. Parceiro não será atualizado..
        /// </summary>
        public static string EmailIBDPInvalid {
            get {
                return ResourceManager.GetString("EmailIBDPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} inválido. Parceiro não será atualizado..
        /// </summary>
        public static string EmailOrbiaInvalid {
            get {
                return ResourceManager.GetString("EmailOrbiaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status da Safra não permite a inclusão de parceiros na safra..
        /// </summary>
        public static string ImportPartnerCropStatusNotAllowed {
            get {
                return ResourceManager.GetString("ImportPartnerCropStatusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API indisponível no momento, por gentileza tentar novamente em alguns minutos.
        /// </summary>
        public static string ImportPartnerCropUnavailableApiPartners {
            get {
                return ResourceManager.GetString("ImportPartnerCropUnavailableApiPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor do campo é Matriz está em branco ou é inválido. Valores válidos para o campo {0}..
        /// </summary>
        public static string InvalidHeadquarterValue {
            get {
                return ResourceManager.GetString("InvalidHeadquarterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna Parceiro Exceção invalido.
        /// </summary>
        public static string InvalidInExceptionValue {
            get {
                return ResourceManager.GetString("InvalidInExceptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sim&quot; ou &quot;Não&quot;.
        /// </summary>
        public static string IsHeadquarterValuesValid {
            get {
                return ResourceManager.GetString("IsHeadquarterValuesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safra não existente.
        /// </summary>
        public static string NoExistCrop {
            get {
                return ResourceManager.GetString("NoExistCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor {0} precisa ter 2 casas decimais..
        /// </summary>
        public static string Not2DecimalPlaces {
            get {
                return ResourceManager.GetString("Not2DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor {0} não é um decimal válido..
        /// </summary>
        public static string NotDecimal {
            get {
                return ResourceManager.GetString("NotDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar ao menos 1 parceiro para o Código do Grupo do Parceiro informado..
        /// </summary>
        public static string PartnerGroupCodeMustHaveOneHeadquarter {
            get {
                return ResourceManager.GetString("PartnerGroupCodeMustHaveOneHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido cadastrar mais de 1 parceiro como matriz para o Código do Grupo do Parceiro informado..
        /// </summary>
        public static string PartnerGroupCodeMustHaveOnlyOneHeadquarter {
            get {
                return ResourceManager.GetString("PartnerGroupCodeMustHaveOnlyOneHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [ Código Grupo Parceiro ] é obrigatório. O Parceiro não será inserido/atualizado..
        /// </summary>
        public static string PartnerGroupCodeRequired {
            get {
                return ResourceManager.GetString("PartnerGroupCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Parceiro {0} não informado ou inválido. Parceiro não será inserido/atualizado..
        /// </summary>
        public static string PartnerTypeInvalid {
            get {
                return ResourceManager.GetString("PartnerTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Parceiro {0} não informado ou inválido. Parceiro não será inserido/atualizado..
        /// </summary>
        public static string PartnerTypeRequired {
            get {
                return ResourceManager.GetString("PartnerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWID {0} não localizado. Parceiro não será atualizado..
        /// </summary>
        public static string RTVMainCWIDInvalid {
            get {
                return ResourceManager.GetString("RTVMainCWIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [ CWID RTV Principal ] é obrigatório. O Parceiro não será inserido/atualizado..
        /// </summary>
        public static string RTVMainCWIDRequired {
            get {
                return ResourceManager.GetString("RTVMainCWIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWID {0} não localizado. Parceiro não será atualizado..
        /// </summary>
        public static string SeedsApproverCWIDInvalid {
            get {
                return ResourceManager.GetString("SeedsApproverCWIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados da coluna Tag Lista de Preços estão incorretos..
        /// </summary>
        public static string TagListPriceInvalid {
            get {
                return ResourceManager.GetString("TagListPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados da coluna Valor Provisão Químicos estão incorretos..
        /// </summary>
        public static string ValueProvisionChemicals {
            get {
                return ResourceManager.GetString("ValueProvisionChemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados da coluna Valor Provisão de KPI estão incorretos..
        /// </summary>
        public static string ValueProvisionKPI {
            get {
                return ResourceManager.GetString("ValueProvisionKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados da coluna Valor Provisão Sementes estão incorretos..
        /// </summary>
        public static string ValueProvisionSeeds {
            get {
                return ResourceManager.GetString("ValueProvisionSeeds", resourceCulture);
            }
        }
    }
}
